{% set name = "pysimdjson" %}
{% set version = "5.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16addc915e4de1da9610206a11f237471e6c3fce6092c1aad7b13f3e36989214

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
  run:
    - python

test:
  imports:
    - simdjson
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/TkTech/pysimdjson
  summary: simdjson bindings for python
  license_file: LICENSE
  license: Apache-2.0 and MIT

extra:
  recipe-maintainers:
    - CJ-Wright
    - synapticarbors
